### ISSUE TITLE
The label of acivity-graph doesn't work.

### ISSUE THREAD

**Issue by HollowGL** [zlysm/zlysm#1]
https://github.com/zlysm/zlysm/blob/7fe8f1f813368d55eae44c2870188a923f508061/README.md?plain=1#L16

> The deployment of the project is moved from `https://activity-graph.herokuapp.com` domain to `https://github-readme-activity-graph.cyclic.app`. In case `https://github-readme-activity-graph.cyclic.app` doesn't work. `Try with https://github-readme-activity-graph.vercel.app`

Refer [this](https://github.com/Ashutosh00710/github-readme-activity-graph?tab=readme-ov-file#%EF%B8%8F-notice-deployment-moved-%EF%B8%8F) for more details.

TL; DR, you could replace `cyclic` with `vercel` to fix the bug.

**Comment by zlysm** [comment]
Very good issue, love from China.
